jobs:
- job: build_geosite
  timeoutInMinutes: 30

  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    GOPATH: '$(system.defaultWorkingDirectory)'

  steps:
  - checkout: none
  - task: GoTool@0
    inputs:
      version: '1.11.2'
  - script: |
      go version
      go get -v -t -d github.com/v2ray/domain-list-community/...
      go run ./src/github.com/v2ray/domain-list-community/main.go
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Generate'
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(system.defaultworkingdirectory)'
      contents: 'dlc.dat'
      targetFolder: '$(build.artifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
